[workspace]
resolver = "2"

members = ["contract-a", "contract-b", "contract-c"]

[workspace.dependencies]
soroban-sdk = { version = "22.0.7" }
contract-a = { path = "contract-a" }
contract-b = { path = "contract-b" }

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true
